version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        logging:
            driver: none
    dispatcher:
        build:
            context: ./dispatcher
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - rabbit
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit