version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        logging:
            driver: none
    redis:
        hostname: redis
        image: redis:3.0
        ports:
            - "6379:6379"
    dispatcher:
        build:
            context: ./dispatcher
            dockerfile: Dockerfile
        links:
            - rabbit
        volumes:
            - /Volumes/Data/Developer/zimfarm/dispatcher/app:/app
        ports:
            - "80:80"
        depends_on:
            - rabbit
            - redis
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
            - redis
    flower:
        build:
            context: ./flower
            dockerfile: Dockerfile
        links:
            - rabbit
        ports:
            - "5555:5555"
        depends_on:
            - rabbit
            - redis